[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = [
    "python -m ensurepip",
    "python -m pip install --upgrade pip",
    "python -m pip install -r requirements.txt"
]

[phases.build]
cmds = ["python -m pip install -r requirements.txt"]

[start]
cmd = "python -m uvicorn src.api.app:app --host 0.0.0.0 --port $PORT"
