[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate && pip install --upgrade pip",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/python -m uvicorn src.api.app:app --host 0.0.0.0 --port $PORT"
